# Generated by Django 4.1.3 on 2022-11-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkateSpotType',
            fields=[
                ('type_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkateSpot',
            fields=[
                ('spot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spots.spot')),
                ('guarded', models.BooleanField(default=False)),
                ('guard_free_time', models.TimeField(default=None, null=True)),
                ('open_alltime', models.BooleanField(default=True)),
                ('open_time', models.TimeField(default=None, null=True)),
                ('close_time', models.TimeField(default=None, null=True)),
                ('type', models.ManyToManyField(related_name='skate_spots', to='spots.skatespottype')),
            ],
            bases=('spots.spot',),
        ),
    ]
