# Generated by Django 4.1.3 on 2022-12-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmxspot',
            old_name='type',
            new_name='specific_type',
        ),
        migrations.RenameField(
            model_name='skatespot',
            old_name='type',
            new_name='specific_type',
        ),
    ]
