# Generated by Django 4.1.3 on 2022-11-14 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from userauth.models import User


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spots', '0002_skatespottype_skatespot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='owner',
            field=models.ForeignKey(
                default=User.objects.get(username='root').id,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spot',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='park_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
