# Generated by Django 4.1.3 on 2022-12-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_rename_type_bmxspot_specific_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottype',
            name='type_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
