# Generated by Django 4.1.3 on 2022-11-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_spot_owner_spot_seen_by_alter_spot_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMXSpotType',
            fields=[
                ('type_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PicnicSpot',
            fields=[
                ('spot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spots.spot')),
                ('seating_provided', models.BooleanField(default=False)),
            ],
            bases=('spots.spot',),
        ),
        migrations.CreateModel(
            name='SunsetSpot',
            fields=[
                ('spot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spots.spot')),
                ('seating', models.BooleanField(default=False)),
            ],
            bases=('spots.spot',),
        ),
        migrations.CreateModel(
            name='WalkSpot',
            fields=[
                ('spot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spots.spot')),
                ('expected_duration', models.FloatField(default=None, null=True)),
                ('path_description', models.TextField(blank=True, default=None, null=True)),
            ],
            bases=('spots.spot',),
        ),
        migrations.CreateModel(
            name='SpotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.spot')),
            ],
        ),
        migrations.CreateModel(
            name='BMXSpot',
            fields=[
                ('spot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spots.spot')),
                ('guarded', models.BooleanField(default=False)),
                ('guard_free_time', models.TimeField(default=None, null=True)),
                ('open_alltime', models.BooleanField(default=True)),
                ('open_time', models.TimeField(default=None, null=True)),
                ('close_time', models.TimeField(default=None, null=True)),
                ('type', models.ManyToManyField(related_name='bmx_spots', to='spots.bmxspottype')),
            ],
            bases=('spots.spot',),
        ),
    ]
