# Generated by Django 4.1.3 on 2022-12-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_alter_spottype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotimage',
            name='image',
            field=models.ImageField(upload_to='spot_images/'),
        ),
        migrations.AlterField(
            model_name='spotimage',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.spotcommon'),
        ),
    ]
