# Generated by Django 4.1.3 on 2022-12-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_alter_spotimage_image_alter_spotimage_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmxspot',
            old_name='guard_free_time',
            new_name='guard_free_from',
        ),
        migrations.RenameField(
            model_name='skatespot',
            old_name='guard_free_time',
            new_name='guard_free_from',
        ),
        migrations.AddField(
            model_name='bmxspot',
            name='guard_free_till',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='skatespot',
            name='guard_free_till',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
