# Generated by Django 4.1.3 on 2022-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_remove_spotcommon_seen_by_spotcommon_displays'),
    ]

    operations = [
        migrations.AddField(
            model_name='spottype',
            name='marker_color',
            field=models.CharField(default='green', max_length=255),
            preserve_default=False,
        ),
    ]
