# Generated by Django 4.1.3 on 2022-12-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0009_spottype_marker_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotimage',
            name='image',
            field=models.ImageField(upload_to='media/spot_images/'),
        ),
    ]
