# Generated by Django 4.1.3 on 2022-12-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to='media/profile_images/'),
            preserve_default=False,
        ),
    ]
