# Generated by Django 4.1.3 on 2022-12-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geo_record',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='geo_total',
            field=models.IntegerField(default=0),
        ),
    ]
